### ISSUE TITLE
Panic in tokio-signal on signal during shutdown

### ISSUE THREAD

**Issue by habnabit** [alexcrichton/tokio-signal#3]
Full output:

```
thread 'main' panicked at 'assertion failed: index < self.len()', ../src/libcore/slice.rs:541
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'bad error on write fd: Broken pipe (os error 32)', /Users/habnabit/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-signal-0.1.0/src/unix.rs:352
stack backtrace:
   1:        0x102667759 - std::sys::backtrace::tracing::imp::write::hd4b54a4a2078cb15
   2:        0x10266d8e0 - std::panicking::default_hook::_{{closure}}::h51a5ee7ba6a9fcef
   3:        0x10266cb70 - std::panicking::default_hook::hf823fce261e27590
   4:        0x10266d196 - std::panicking::rust_panic_with_hook::h8d486474663979b9
   5:        0x10266cfe4 - std::panicking::begin_panic::h72862f004a4942ab
   6:        0x10266cf42 - std::panicking::begin_panic_fmt::hdc424a357d9142e1
   7:        0x1023cdc73 - tokio_signal::unix::handler::h5a63620a2e3746db
   8:     0x7fff984c7529 - _sigtramp
   9:        0x1023c4cbc - _<futures..sync..oneshot..Receiver<T> as core..ops..Drop>::drop::h79bfb14f6bb18870
  10:        0x1023b6acd - drop::h9823164f76363842
  11:        0x1023b6528 - drop::h81df0a3bc0f8e991
  12:        0x1023b842c - drop::he7e7c8b8ad1347a2
  13:        0x1023b6cc0 - drop::h9d359c1420935c5d
  14:        0x1023b79f7 - drop::hc8e4c3c1eda7741b
  15:        0x1023c0a66 - _<collections..vec..Vec<T> as core..ops..Drop>::drop::h2492fdc09a201d80
  16:        0x1023b7250 - drop::hb1929594a6d3d609
  17:        0x1023b84ac - drop::hee1be633ccfbe89a
  18:        0x1023b56c2 - drop::h3ffe77843dd276e9
  19:        0x1023b81ea - drop::hdf9e68733ee9a73a
  20:        0x101fcc10f - drop::h491ab2d1ee9e604e
  21:        0x101fcb720 - drop::h368bb9c7a20a0269
  22:        0x101fcc4c0 - drop::h5aabc44887564d96
  23:        0x101fca9cb - drop::h12ec0837c8ae5f26
  24:        0x101fcf25d - drop::hd7f5239d1e5d58b8
  25:        0x101fcda57 - drop::h9368b2674f2f871d
  26:        0x101fcad77 - drop::h1b18c08069327275
  27:        0x101fdb986 - _<collections..vec..Vec<T> as core..ops..Drop>::drop::hfe878ab6e29f169f
  28:        0x101fcd310 - drop::h80241d0c5338d0b5
  29:        0x101fcdaf8 - drop::h9552857465df47de
  30:        0x101fca40a - drop::h04b41571e720104d
  31:        0x101fcf318 - drop::hda48127395869dde
  32:        0x101fcd5ac - drop::h83316f1ff44c36fc
  33:        0x101fd3e8d - _<alloc..rc..Rc<T> as core..ops..Drop>::drop::h82cc1150e6f2dbbc
  34:        0x101fcf420 - drop::hde13610683ca7012
  35:        0x101fca57a - drop::h066e44742f821d6f
  36:        0x101fec042 - hab_prompt_utils::run_in_loop::h3c56596c9bd2e886
  37:        0x101fecd1e - hab_prompt_utils::main::h474eb2a9f22186d9
  38:        0x10266deca - __rust_maybe_catch_panic
  39:        0x10266c63e - std::rt::lang_start::hca48e539ce72a288
  40:        0x101ff1079 - main
thread panicked while panicking. aborting.
```

I'm 90% sure the signal being received here is `SIGCHLD`, since there's often a child process running. From gitter:

>Aaron Gallagher @habnabit 17:15
>from my superficial understanding, it seems you'd want DriverTask::drop to remove the associated GlobalState entry
>so you remove the read and write ends of the pipe at the same time

>Alex Crichton @alexcrichton 17:16
>habnabit: yeah makes sense

**Comment by alexcrichton** [comment]
Thanks for the report! Want to test out the fix and confirm it works locally for you?

**Comment by alexcrichton** [comment]
er, didn't mean to reopen

**Comment by habnabit** [comment]
Looks like it works! Thanks.
